---
version: 2

jobs:
  build:
    working_directory: /go/src/zvelo.io/cobratest

    docker:
      - image: circleci/golang:latest

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            go get github.com/magefile/mage
            go get github.com/golang/dep/cmd/dep
            go get github.com/mattn/goveralls
            dep ensure
      - setup_remote_docker
      - run:
          name: Calculate unit test coverage
          command: |
            mage -v coverOnly
            goveralls -v -coverprofile=.coverage-all.out -service circle-ci -repotoken ${COVERALLS_REPO_TOKEN} || true
      - run: mage -v image
      - deploy:
          name: Push images to docker hub
          command: |
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
            mage -v deploy
